theme: jekyll-theme-midnight
title: @asfarian
description: I focus on empowering people with technology. A human-computer interaction researcher who active in ACM SIGCHI. A student affair officers who enjoy elevating the lower bound of the student creativity, competency, and soft skills.
